workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: morador.app
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 22.13.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm install
      - name: Capacitor sync
        script: |
          node -v
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - ia.oliveira.click@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-capacitor-workflow:
    name: Android Capacitor Build
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.oliveiraclick.appmorador"
      node: 22.13.0
    scripts:
      - name: Install dependencies
        script: |
          node -v
          npm install
      - name: Capacitor sync
        script: |
          node -v
          npx cap sync android
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ia.oliveira.click@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
