-- Create banners table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  title TEXT,
  link_url TEXT,
  active BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public read access for banners" ON public.banners
  FOR SELECT USING (true);

CREATE POLICY "Admin write access for banners" ON public.banners
  FOR ALL USING (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role in ('admin', 'super_admin')
    )
  );

-- Insert a placeholder banner if table is empty (so carousel isn't blank)
INSERT INTO public.banners (image_url, title, active, display_order)
SELECT 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=1200&q=80', 'Bem-vindo ao Condomínio!', true, 1
WHERE NOT EXISTS (SELECT 1 FROM public.banners);
