-- Create reviews table
create table reviews (
  id bigint generated by default as identity primary key,
  provider_id uuid references auth.users not null,
  resident_id uuid references auth.users not null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create marketplace_products table (Provider selling items)
create table marketplace_products (
  id bigint generated by default as identity primary key,
  provider_id uuid references auth.users not null,
  title text not null,
  description text,
  price numeric(10,2) not null,
  image_url text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table reviews enable row level security;
alter table marketplace_products enable row level security;

-- Policies for Reviews
create policy "Public read reviews" on reviews for select using (true);
create policy "Residents insert reviews" on reviews for insert with check (auth.uid() = resident_id);

-- Policies for Products
create policy "Public read products" on marketplace_products for select using (true);
create policy "Providers manage own products" on marketplace_products for all using (auth.uid() = provider_id);
