-- Create access_control table
create table access_control (
  id bigint generated by default as identity primary key,
  resident_id uuid references auth.users not null,
  visitor_name text not null,
  type text not null, -- 'Visita' or 'Serviço'
  date text not null, -- Store as string for simplicity or date type
  status text default 'Pendente', -- 'Pendente', 'Autorizado', 'Entrou'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table access_control enable row level security;

-- Policies
create policy "Residents can view their own visitors"
  on access_control for select
  using (auth.uid() = resident_id);

create policy "Residents can add visitors"
  on access_control for insert
  with check (auth.uid() = resident_id);

create policy "Admins/Portaria can view all"
  on access_control for select
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins/Portaria can update status"
  on access_control for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );
