-- CLEANUP (Force schema update)
drop table if exists public.reservations cascade;
drop table if exists public.service_requests cascade;
drop table if exists public.access_control cascade;

create table public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  area_id text not null,
  area_name text not null,
  date date not null,
  status text default 'confirmed',
  resident_id uuid references auth.users not null,
  unit text,
  tower text
);

alter table public.reservations enable row level security;
create policy "Residents can view all reservations" on public.reservations for select using (true);
create policy "Residents can insert their own reservations" on public.reservations for insert with check (auth.uid() = resident_id);
create policy "Residents can delete their own reservations" on public.reservations for delete using (auth.uid() = resident_id);

create table public.service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  category text,
  status text default 'pending',
  resident_id uuid references auth.users not null,
  professional_id uuid references auth.users,
  unit text,
  location text,
  date date default timezone('utc'::text, now())::date
);

alter table public.service_requests enable row level security;
create policy "Residents can view their own requests" on public.service_requests for select using (auth.uid() = resident_id);
create policy "Residents can insert requests" on public.service_requests for insert with check (auth.uid() = resident_id);
create policy "Professionals can view open requests" on public.service_requests for select using (true);
create policy "Professionals can update requests" on public.service_requests for update using (true);

create table public.access_control (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  visitor_name text not null,
  type text not null,
  date date not null,
  status text default 'Autorizado',
  resident_id uuid references auth.users not null,
  unit text,
  tower text,
  avatar_url text
);

alter table public.access_control enable row level security;
create policy "Residents can view their own access list" on public.access_control for select using (auth.uid() = resident_id);
create policy "Residents can insert access" on public.access_control for insert with check (auth.uid() = resident_id);
create policy "Admins/Concierge can view all" on public.access_control for select using (true);
