-- Create maintenance_tickets table for Condo Internal Issues
create table maintenance_tickets (
  id bigint generated by default as identity primary key,
  resident_id uuid references auth.users not null,
  title text not null,
  description text,
  category text not null, -- 'Elétrica', 'Limpeza', 'Segurança', 'Outros'
  status text default 'Aberto', -- 'Aberto', 'Em Andamento', 'Concluído'
  location text, -- 'Bloco A', 'Hall', etc.
  photos text[], -- Array of URLs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table maintenance_tickets enable row level security;

-- Policies
create policy "Residents can view their own tickets"
  on maintenance_tickets for select
  using (auth.uid() = resident_id);

create policy "Residents can create tickets"
  on maintenance_tickets for insert
  with check (auth.uid() = resident_id);

create policy "Admins/Portaria can view all tickets"
  on maintenance_tickets for select
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can update tickets"
  on maintenance_tickets for update
  using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );
